### ISSUE TITLE
Visitor: Project's details page / (User: Comment and rate existing project in the library.)

### ISSUE THREAD

**Issue by sinatra-ms** [sinatra-pod/moringa-library#6]

**Comment by kiprotichdominic** [comment]
Done waiting for review

**Comment by kiprotichdominic** [comment]
https://www.figma.com/file/bnJw1TntsQCzGDeDWsg0V5/Moringa-Library?node-id=126%3A104&t=vSwQeuUnzISAkenB-0

**Comment by otsembo** [comment]
@kiprotichdominic There are some few changes for you:

- [ ] Use the new Navigation bar available in the file
- [ ] Use the new Footer.
- [ ] Ensure navbar stretches left to right.
- [ ] Ensure description contains an image just  to make it look lively. Example => [here](https://devlibrary.withgoogle.com/products/android/repos/GetStream-webrtc-android)
- [ ] Move the comment section to the side, since the description can be as long as possible.
- [ ] No need to show project status since it is a visitor account.
- [ ] Small note (There is a banner image and images inside the description since it will be markup as opposed to plain text)

**Comment by kiprotichdominic** [comment]
Did not understand  this: **There is a banner image and images inside the description since it will be markup as opposed to plain text**

**Comment by kiprotichdominic** [comment]
@otsembo  Kindly review

**Comment by otsembo** [comment]
@kiprotichdominic There are a few changes needed:

- [ ] Let text overlay extend the full width as opposed to just half.
- [ ] Communicate with @KelvinMuriithi and add the rating section to the page.
- [ ] Use sample data instead of the generic text. Make it have a good feel and vibe.
- [ ] Make the `update` button to portray a `Call To Action` (Visible and locatable easily)
- [ ] Use appropriate footer.
- [ ] Replace these metadata in the top description portion 

![Image](https://user-images.githubusercontent.com/38042565/225421391-8264045a-b082-4743-be5c-5eb5e78a4f0e.png)
